
version: '3.4'
services:
  apimysqldocker:
    image:  apimovie:dev
    container_name: apimovie
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    command: ["dotnet", "ef", "database update"] 
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: mysql
    container_name: mysqldbmovie
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: movie

volumes:
  db-volume: